world: world
door-X: -247
door-Y: 70
door-Z: -140
random-door-X: -286
random-door-Y: 70
random-door-Z: -148
blue-door-X: -284
blue-door-Y: 70
blue-door-Z: -148
red-door-X: -282
red-door-Y: 70
red-door-Z: -148
spectator-door-X: -285
spectator-door-Y: 71
spectator-door-Z: -147
team-choose-spawn-X: -283
team-choose-spawn-Y: 70
team-choose-spawn-Z: -144
blue-sign-X: -284
blue-sign-Y: 72
blue-sign-Z: -147
red-sign-X: -282
red-sign-Y: 72
red-sign-Z: -147