name: MF2
author: RubbaBoy
main: com.uddernetworks.tf2.main.Main
version: 0.14b
website: http://www.uddernetworks.com/minefortress-2
description: A port of the game Team Fortress 2 in minecraft for Uddernetworks!
commands:
   tf2:
      description: Runs the MF2 command.
      usage: /mf2